language: rust

rust:
- stable
- nightly

addons:
  apt:
    packages:
    - debhelper
    - fakeroot
    - libdbus-1-dev

cache:
  cargo: true

script:
- cargo build --all
- cargo test --all

jobs:
  allow_failures:
  - rust: nightly-2019-09-03

  include:
  - stage: clippy lints
    rust: nightly-2019-09-03
    before_install:
    - rustup component add clippy
    script:
    - cargo clippy --all -- -D warnings

  - stage: release
    if: tag IS present
    script:
    - rm -f "./pkg/deb/*.deb" "./pkg/bin/*.tar.xz"
    - ./pkg/deb/makedeb
    - ./pkg/bin/makebin
    deploy:
      provider: releases

      file_glob: true
      file:
      - "./pkg/deb/*.deb"
      - "./pkg/bin/*.tar.xz"

      api_key:
        secure: FhHK/YJHl79S8BaezSLvGo7bHH+XDbiT0T5rZftua9jW0vhSZWgUmqnGXlw9LjXJRGjB2/xPPtnowif1F75y62IDwAqmbvwI20pulZCqYwRJPesGb/61k3ELo/y0PI69jWnO8BqFEvxt7fi3yDJsSUTUFkCb3ekLi7PBtltA3HmzVsj1wLOCu14pJdJqVRhcu6NdZY57tIbGcoygdfE8MPh+B4EbiJA+nI9yEnV4mrD413iymiZNuEF79sXUDVxVkv0++m0hll/M4UW1GA/i474DZ2C2KWQK9MARJzwWJj0PIGtRbYa21r/40bmFjTOFAaeoBs0khtyMMSZlR5tIEqSmMFHztJsLGQhpq8fwTm9JC2TSh7mYKyeW0YcHoJhd1IAgUgBaHzGJSPg6ktrMheKkTUAdYEQPQK0RW0gK+oBAtJEcU+CSOmoa32bO/Hw/UtUt0vQS5q0PE8M0Nx7aLkYNXgEfHn9zFc9i1f9Z6RwaSIljKa12uksW5lcfrimSV6LZadetdutSMNzalpRb5LgPXTAS1jdzPhNYYODbaausScYxe/LO1+5hS/dM72rgGC2GKZHu+Y5nCMAbMlHxVzYPw5h0xP/dnEynRUHF/CH1BZVwP0/C1ENN99oV0HSXfTU7BrasPlmd3BDSst0dunpTdCyyP2A3nLIftaX4ozI=

      skip_cleanup: true
      draft: true
      on:
        tags: true

branches:
  only:
  - master
  - ci
  - "/^v\\d.*/"
  - "/^testing.ci\\.*/"

notifications:
  email:
    on_success: never
