[package]
name = "surface-dtx-userd"
version = "0.1.2"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/qzed/linux-surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.0"
dbus = "0.6.5"
dbus-tokio = "0.3.0"
failure = "0.1.5"
serde = { version = "1.0.99", features = ['derive'] }
slog = { version = "2.5.2", features = ['release_max_level_debug'] }
slog-term = "2.4.1"
tokio = "0.1.22"
toml = "0.5.3"

[build-dependencies]
clap = "2.33.0"
