[package]
name = "surface-dtx-userd"
version = "0.3.1"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.43"
atty = "0.2.14"
clap = "2.33.3"
dbus = "0.9.3"
dbus-tokio = "0.7.4"
futures = "0.3.16"
serde = { version = "1.0.128", features = ["derive"] }
serde_ignored = "0.1.2"
tokio = { version = "1.10.0", features = ["macros", "rt", "signal"] }
toml = "0.5.8"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"

[build-dependencies]
clap = "2.33.3"
