[package]
name = "surface-dtx-userd"
version = "0.3.4"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.11", features = ["cargo"] }
dbus = "0.9.7"
dbus-tokio = "0.7.6"
futures = "0.3.28"
serde = { version = "1.0.171", features = ["derive"] }
serde_ignored = "0.1.8"
tokio = { version = "1.29.1", features = ["macros", "rt", "signal"] }
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }

[build-dependencies]
clap = "4.3.11"
clap_complete = "4.3.2"
