[package]
name = "surface-dtx-userd"
version = "0.3.3"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.65"
atty = "0.2.14"
clap = { version = "3.2.22", features = ["cargo"] }
dbus = "0.9.6"
dbus-tokio = "0.7.5"
futures = "0.3.24"
serde = { version = "1.0.145", features = ["derive"] }
serde_ignored = "0.1.5"
tokio = { version = "1.23.1", features = ["macros", "rt", "signal"] }
toml = "0.5.9"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["std", "env-filter"] }

[build-dependencies]
clap = "3.2.22"
clap_complete = "3.2.5"
