[package]
name = "surface-dtx-userd"
version = "0.1.0"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
toml = "0.5.0"

[build-dependencies]
clap = "2.33.0"
