[package]
name = "surface-dtx-userd"
version = "0.3.4"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.70"
atty = "0.2.14"
clap = { version = "4.2.3", features = ["cargo"] }
dbus = "0.9.7"
dbus-tokio = "0.7.6"
futures = "0.3.28"
serde = { version = "1.0.160", features = ["derive"] }
serde_ignored = "0.1.7"
tokio = { version = "1.27.0", features = ["macros", "rt", "signal"] }
toml = "0.7.3"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["std", "env-filter"] }

[build-dependencies]
clap = "4.2.3"
clap_complete = "4.2.0"
