[package]
name = "surface-dtx-userd"
version = "0.1.5"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.1"
dbus = "0.8.4"
dbus-tokio = "0.5.1"
failure = "0.1.8"
serde = { version = "1.0.114", features = ['derive'] }
slog = { version = "2.5.2", features = ['release_max_level_debug'] }
slog-term = "2.6.0"
tokio = { version = "0.2.21", features=["time", "macros", "io-driver", "rt-core", "rt-util", "rt-threaded", "stream", "blocking"]}
toml = "0.5.6"
futures-util = "0.3.5"
futures = "0.3.5"

[build-dependencies]
clap = "2.33.1"
