[package]
name = "surface-dtx-userd"
version = "0.2.0"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.3"
dbus = "0.9.2"
dbus-tokio = "0.7.3"
failure = "0.1.8"
serde = { version = "1.0.124", features = ["derive"] }
slog = { version = "2.7.0", features = ["release_max_level_debug"] }
slog-term = "2.8.0"
tokio = { version = "1.4.0", features = ["macros", "rt"] }
toml = "0.5.8"
futures = "0.3.13"

[build-dependencies]
clap = "2.33.3"
