[package]
name = "surface-dtx-userd"
version = "0.2.0"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.39"
atty = "0.2.14"
clap = "2.33.3"
dbus = "0.9.2"
dbus-tokio = "0.7.3"
futures = "0.3.13"
serde = { version = "1.0.125", features = ["derive"] }
serde_ignored = "0.1.2"
tokio = { version = "1.4.0", features = ["macros", "rt", "signal"] }
toml = "0.5.8"
tracing = "0.1.25"
tracing-subscriber = "0.2.17"

[build-dependencies]
clap = "2.33.3"
