[package]
name = "surface-dtx-userd"
version = "0.3.1"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.57"
atty = "0.2.14"
clap = { version = "3.1.12", features = ["cargo"] }
dbus = "0.9.5"
dbus-tokio = "0.7.5"
futures = "0.3.21"
serde = { version = "1.0.136", features = ["derive"] }
serde_ignored = "0.1.2"
tokio = { version = "1.18.0", features = ["macros", "rt", "signal"] }
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["std", "env-filter"] }

[build-dependencies]
clap = "3.1.12"
clap_complete = "3.1.2"
