[package]
name = "surface-dtx-userd"
version = "0.1.5"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) User Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.3"
dbus = { git = "https://github.com/diwic/dbus-rs.git", tag = "dbus-v0.9.0" }
dbus-tokio = { git = "https://github.com/diwic/dbus-rs.git", tag = "dbus-v0.9.0" }
failure = "0.1.8"
serde = { version = "1.0.116", features = ["derive"] }
slog = { version = "2.5.2", features = ["release_max_level_debug"] }
slog-term = "2.6.0"
tokio = { version = "0.2.22", features = ["stream"] }
toml = "0.5.6"
futures = "0.3.6"

[build-dependencies]
clap = "2.33.3"
