[package]
name = "surface-dtx-daemon"
version = "0.3.3"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.70"
atty = "0.2.14"
clap = { version = "4.2.3", features = ["cargo"] }
dbus = "0.9.7"
dbus-tokio = "0.7.6"
dbus-crossroads = "0.5.2"
futures = "0.3.28"
libc = "0.2.141"
nix = "0.26.2"
sdtx = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.3" }
sdtx-tokio = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.3" }
serde = { version = "1.0.160", features = ['derive'] }
tokio = { version = "1.27.0", features = ["fs", "sync", "process", "signal", "io-util", "rt", "macros"] }
toml = "0.7.3"
serde_ignored = "0.1.7"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["std", "env-filter"] }

[build-dependencies]
clap = "4.2.3"
clap_complete = "4.2.0"
