[package]
name = "surface-dtx-daemon"
version = "0.3.3"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.65"
atty = "0.2.14"
clap = { version = "3.2.22", features = ["cargo"] }
dbus = "0.9.6"
dbus-tokio = "0.7.5"
dbus-crossroads = "0.5.1"
futures = "0.3.24"
libc = "0.2.134"
nix = "0.25.0"
sdtx = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.3" }
sdtx-tokio = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.3" }
serde = { version = "1.0.145", features = ['derive'] }
tokio = { version = "1.24.2", features = ["fs", "sync", "process", "signal", "io-util", "rt", "macros"] }
toml = "0.5.9"
serde_ignored = "0.1.5"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["std", "env-filter"] }

[build-dependencies]
clap = "3.2.22"
clap_complete = "3.2.5"
