[package]
name = "surface-dtx-daemon"
version = "0.2.0"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.39"
clap = "2.33.3"
dbus = "0.9.2"
dbus-tokio = "0.7.3"
dbus-crossroads = "0.3.0"
futures = "0.3.13"
libc = "0.2.91"
nix = "0.20.0"
sdtx = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.2" }
sdtx-tokio = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.2" }
serde = { version = "1.0.125", features = ['derive'] }
tokio = { version = "1.4.0", features = ["fs", "sync", "process", "signal", "io-util", "rt", "macros"] }
toml = "0.5.8"
serde_ignored = "0.1.2"
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
atty = "0.2.14"

[build-dependencies]
clap = "2.33.3"
