[package]
name = "surface-dtx-daemon"
version = "0.3.0"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) Daemon"

repository = "https://github.com/linux-surface/surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.43"
atty = "0.2.14"
clap = "2.33.3"
dbus = "0.9.3"
dbus-tokio = "0.7.4"
dbus-crossroads = "0.4.0"
futures = "0.3.16"
libc = "0.2.100"
nix = "0.22.1"
sdtx = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.2" }
sdtx-tokio = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.2" }
serde = { version = "1.0.128", features = ['derive'] }
tokio = { version = "1.10.0", features = ["fs", "sync", "process", "signal", "io-util", "rt", "macros"] }
toml = "0.5.8"
serde_ignored = "0.1.2"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"

[build-dependencies]
clap = "2.33.3"
