[package]
name = "surface-dtx-daemon"
version = "0.1.2"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Surface Detachment System (DTX) Daemon"

repository = "https://github.com/qzed/linux-surface-dtx-daemon/"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.0"
dbus = "0.6.4"
dbus-tokio = "0.3.0"
failure = "0.1.5"
libc = "0.2.58"
nix = "0.14.1"
serde = { version = "1.0.94", features = ['derive'] }
slog = { version = "2.4.1", features = ['release_max_level_debug'] }
slog-term = "2.4.0"
tokio = "0.1.22"
tokio-file-unix = "0.5.1"
tokio-process = "0.2.4"
tokio-signal = "0.2.7"
tokio-timer = "0.2.11"
toml = "0.5.1"

[build-dependencies]
clap = "2.33.0"
