# Surface DTX System Daemon Configuration


[log]
# Log format options.

level = "info"
#   The level used for logging.
#   Valid options are trace, debug, info, warning, error, and critical.


[handler]
# Event handler scripts.
# All paths are relative to this file.

[handler.detach]
exec = "./detach.sh"
#   The executable to be executed before unlocking the clipboard.
#   If unspecified, no handler will be executed.

#timeout = <numeric>
#   Timeout for the executable, after which it will be killed.
#   Defaults to 60 seconds.

[handler.detach_abort]
exec = "./attach.sh"
#   The executable to be executed after the detach-process has been aborted.
#   This script will be executed only after completion of the detach script.
#   If unspecified, no handler will be executed.

#timeout = <numeric>
#   Timeout for the executable, after which it will be killed.
#   Defaults to 60 seconds.

[handler.attach]
exec = "./attach.sh"
#   The executable to be executed after the clipboard has been attached.
#   Before execution, the delay specified in delay.attach will be waited to
#   allow for all devices to be set up correctly.
#   If unspecified, no handler will be executed.

#timeout = <numeric>
#   Timeout for the executable, after which it will be killed.
#   Defaults to 60 seconds.

#delay = <numeric>
#   The delay in seconds to wait before executing the attach handler.
#   Defaults to 5 (seconds).
