name: CI

on:
  push:
    branches:
      - master
      - feature/ci

  pull_request:

  create:
    tags:

jobs:
  lint:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rust
      run: |
        rustup update stable && rustup default stable
        rustup component add clippy

    - name: Install dependencies
      run: sudo apt-get install libdbus-1-dev

    - name: Run clippy
      run: cargo clippy --all --all-features -- -Dwarnings

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

    - name: Install dependencies
      run: sudo apt-get install libdbus-1-dev

    - name: Build
      run: cargo build --all

    - name: Test
      run: cargo test --all
