name: CI

on:
  push:
    branches:
      - master
      - feature/ci

    tags:
      - v[0-9]+.*
      - testing-ci.*

  pull_request:

jobs:
  lint:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rust
      run: |
        rustup update stable && rustup default stable
        rustup component add clippy

    - name: Install dependencies
      run: sudo apt-get install libdbus-1-dev

    - name: Run clippy
      run: cargo clippy --all --all-features -- -Dwarnings -Aclippy::unnecessary_wraps

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

    - name: Install dependencies
      run: sudo apt-get install libdbus-1-dev

    - name: Build
      run: cargo build --all

    - name: Test
      run: cargo test --all

  build-bin:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')

    name: Build binary package
    runs-on: ubuntu-16.04
    needs: [lint, test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rust
      run: rustup update stable && rustup default stable

    - name: Install dependencies
      run: sudo apt-get install libdbus-1-dev

    - name: Build package
      run: ./pkg/bin/makebin

    - name: Prepare release
      run: mkdir release && mv pkg/bin/*.tar.xz release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: binary-latest
        path: release

  build-deb:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')

    name: Build deb package
    runs-on: ubuntu-16.04
    needs: [lint, test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rust
      run: rustup update stable && rustup default stable

    - name: Install dependencies
      run: sudo apt-get install debhelper fakeroot dpkg-sig libdbus-1-dev

    - name: Build package
      run: ./pkg/deb/makedeb

    - name: Sign package
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: |
        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes
        export GPG_TTY=$(tty)
        # sign package
        cd pkg/deb && dpkg-sig -g "--batch --no-tty" --sign builder -k $GPG_KEY_ID ./*.deb
    - name: Prepare release
      run: mkdir release && mv pkg/deb/*.deb release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: debian-latest
        path: release

  build-f34:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')

    name: Build Fedora 34 package
    runs-on: ubuntu-latest
    needs: [lint, test]
    container: fedora:34

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        dnf distro-sync -y
        dnf install -y rpmdevtools rpm-sign 'dnf-command(builddep)'
        dnf builddep -y pkg/fedora/surface-dtx-daemon.spec

    - name: Build package
      run: |
        cd pkg/fedora
        # Build the .rpm packages
        ./makerpm

    - name: Sign packages
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: |
        cd pkg/fedora/out/x86_64

        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes

        # sign package
        rpm --resign *.rpm --define "_gpg_name $GPG_KEY_ID"

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fedora-34-latest
        path: pkg/fedora/out/x86_64

  build-f33:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')

    name: Build Fedora 33 package
    runs-on: ubuntu-latest
    needs: [lint, test]
    container: fedora:33

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        dnf distro-sync -y
        dnf install -y rpmdevtools rpm-sign 'dnf-command(builddep)'
        dnf builddep -y pkg/fedora/surface-dtx-daemon.spec

    - name: Build package
      run: |
        cd pkg/fedora
        # Build the .rpm packages
        ./makerpm

    - name: Sign packages
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: |
        cd pkg/fedora/out/x86_64

        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes

        # sign package
        rpm --resign *.rpm --define "_gpg_name $GPG_KEY_ID"

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fedora-33-latest
        path: pkg/fedora/out/x86_64

  build-f32:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')

    name: Build Fedora 32 package
    runs-on: ubuntu-latest
    needs: [lint, test]
    container: fedora:32

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        dnf distro-sync -y
        dnf install -y rpmdevtools rpm-sign 'dnf-command(builddep)'
        dnf builddep -y pkg/fedora/surface-dtx-daemon.spec

    - name: Build package
      run: |
        cd pkg/fedora
        # Build the .rpm packages
        ./makerpm

    - name: Sign packages
      env:
        GPG_KEY_ID: 56C464BAAC421453
        GPG_KEY: ${{ secrets.SURFACE_GPG_KEY }}
      run: |
        cd pkg/fedora/out/x86_64

        # import GPG key
        echo "$GPG_KEY" | base64 -d | gpg --import --no-tty --batch --yes

        # sign package
        rpm --resign *.rpm --define "_gpg_name $GPG_KEY_ID"

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: fedora-32-latest
        path: pkg/fedora/out/x86_64

  release:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')

    name: Publish release
    needs: [build-bin, build-deb, build-f34, build-f33, build-f32]
    runs-on: ubuntu-latest

    steps:
    - name: Download binary artifacts
      uses: actions/download-artifact@v1
      with:
        name: binary-latest

    - name: Download Debian artifacts
      uses: actions/download-artifact@v1
      with:
        name: debian-latest

    - name: Download Fedora 34 artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-34-latest

    - name: Download Fedora 33 artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-33-latest

    - name: Download Fedora 32 artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-32-latest

    - name: Upload assets
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*-latest/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  repo-deb:
    name: Update Debian package repository
    needs: [release]
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y git

    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: debian-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
        BRANCH_STAGING: u/staging
        GIT_REF: ${{ github.ref }}
      run: |
        repo="https://surfacebot:${SURFACEBOT_TOKEN}@github.com/linux-surface/repo.git"

        # clone package repository
        git clone -b "${BRANCH_STAGING}" "${repo}" repo

        # copy packages
        cp debian-latest/* repo/debian/
        cd repo/debian

        # parse git tag from ref
        GIT_TAG=$(echo $GIT_REF | sed 's|^refs/tags/||g')

        # convert packages into references
        for pkg in $(find . -name '*.deb'); do
          echo "surface-dtx-daemon:$GIT_TAG/$(basename $pkg)" > $pkg.blob
          rm $pkg
        done

        # set git identity
        git config --global user.email "surfacebot@users.noreply.github.com"
        git config --global user.name "surfacebot"

        # commit and push
        update_branch="${BRANCH_STAGING}-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
        git switch -c "${update_branch}"
        git add .
        git commit -m "Update Debian DTX daemon"
        git push --set-upstream origin "${update_branch}"

  repo-f34:
    name: Update Fedora 34 package repository
    needs: [release]
    runs-on: ubuntu-latest
    container: fedora:34
    steps:
    - name: Install dependencies
      run: |
        dnf install -y git findutils

    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-34-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
        BRANCH_STAGING: u/staging
        GIT_REF: ${{ github.ref }}
      run: |
        repo="https://surfacebot:${SURFACEBOT_TOKEN}@github.com/linux-surface/repo.git"

        # clone package repository
        git clone -b "${BRANCH_STAGING}" "${repo}" repo

        # copy packages
        cp fedora-34-latest/* repo/fedora/f34
        cd repo/fedora/f34

        # parse git tag from ref
        GIT_TAG=$(echo $GIT_REF | sed 's|^refs/tags/||g')

        # convert packages into references
        for pkg in $(find . -name '*.rpm'); do
          echo "surface-dtx-daemon:$GIT_TAG/$(basename $pkg)" > $pkg.blob
          rm $pkg
        done

        # set git identity
        git config --global user.email "surfacebot@users.noreply.github.com"
        git config --global user.name "surfacebot"

        # commit and push
        update_branch="${BRANCH_STAGING}-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
        git checkout -b "${update_branch}"
        git add .
        git commit -m "Update Fedora 34 DTX daemon"
        git push --set-upstream origin "${update_branch}"

  repo-f33:
    name: Update Fedora 33 package repository
    needs: [release]
    runs-on: ubuntu-latest
    container: fedora:33
    steps:
    - name: Install dependencies
      run: |
        dnf install -y git findutils

    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-33-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
        BRANCH_STAGING: u/staging
        GIT_REF: ${{ github.ref }}
      run: |
        repo="https://surfacebot:${SURFACEBOT_TOKEN}@github.com/linux-surface/repo.git"

        # clone package repository
        git clone -b "${BRANCH_STAGING}" "${repo}" repo

        # copy packages
        cp fedora-33-latest/* repo/fedora/f33
        cd repo/fedora/f33

        # parse git tag from ref
        GIT_TAG=$(echo $GIT_REF | sed 's|^refs/tags/||g')

        # convert packages into references
        for pkg in $(find . -name '*.rpm'); do
          echo "surface-dtx-daemon:$GIT_TAG/$(basename $pkg)" > $pkg.blob
          rm $pkg
        done

        # set git identity
        git config --global user.email "surfacebot@users.noreply.github.com"
        git config --global user.name "surfacebot"

        # commit and push
        update_branch="${BRANCH_STAGING}-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
        git checkout -b "${update_branch}"
        git add .
        git commit -m "Update Fedora 33 DTX daemon"
        git push --set-upstream origin "${update_branch}"

  repo-f32:
    name: Update Fedora 32 package repository
    needs: [release]
    runs-on: ubuntu-latest
    container: fedora:32
    steps:
    - name: Install dependencies
      run: |
        dnf install -y git findutils

    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: fedora-32-latest

    - name: Update repository
      env:
        SURFACEBOT_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
        BRANCH_STAGING: u/staging
        GIT_REF: ${{ github.ref }}
      run: |
        repo="https://surfacebot:${SURFACEBOT_TOKEN}@github.com/linux-surface/repo.git"

        # clone package repository
        git clone -b "${BRANCH_STAGING}" "${repo}" repo

        # copy packages
        cp fedora-32-latest/* repo/fedora/f32
        cd repo/fedora/f32

        # parse git tag from ref
        GIT_TAG=$(echo $GIT_REF | sed 's|^refs/tags/||g')

        # convert packages into references
        for pkg in $(find . -name '*.rpm'); do
          echo "surface-dtx-daemon:$GIT_TAG/$(basename $pkg)" > $pkg.blob
          rm $pkg
        done

        # set git identity
        git config --global user.email "surfacebot@users.noreply.github.com"
        git config --global user.name "surfacebot"

        # commit and push
        update_branch="${BRANCH_STAGING}-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
        git checkout -b "${update_branch}"
        git add .
        git commit -m "Update Fedora 32 DTX daemon"
        git push --set-upstream origin "${update_branch}"
